apiVersion: v1
kind: ConfigMap
metadata:
  name: tep-app-config
  namespace: myargocd
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_HOST: "mysql.tep.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "tep_db"
