apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-tep
  labels:
    app: tep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tep
  template:
    metadata:
      labels:
        app: tep
    spec:
      initContainers:
        - name: git-clone
          image: alpine/git:latest
          command: ["/bin/sh","-c","git clone --depth 1 https://github.com/doladoli/tep.git /var/www/html"]
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
        - name: composer-install
          image: composer:2
          command: ["/bin/sh","-c","composer install --no-dev --prefer-dist -d /var/www/html"]
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
      containers:
        - name: php
          image: php:8.1-apache
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: tep-app-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tep-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tep-db-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
      volumes:
        - name: app-code
          emptyDir: {}
